"""
part_resolved_anatomy.py -- BONE FOR BONE + MUSCLE FOR MUSCLE: the lifting step P.

axial_skeleton.py gave the model's cartilage cells individual vertebra IDENTITIES but only 23/30 came out
populated (sparse mid-column cartilage). This module does the LIFTING P (named part -> cells) for the two
serially/roster-enumerated systems so every named part is occupied:

  VERTEBRAE  -- complete all 30 (C1..C7, T1..T13, L1..L6, S1..S4): the model's cartilage cells fill the
                vertebrae they grew; the empty ones are LIFTED (a small centrum synthesised on the axial
                centre-line at the interpolated level). Positions are warped to the atlas AP spacing by name.
  MUSCLES    -- the atlas's 31 Hill-muscles are each a named origin->insertion segment; the model's
                myotome (Muscle-fate) cells are assigned to the nearest muscle IN NORMALISED AP/DV/ML space
                (frame-robust), giving each muscle the model's cells. Muscles with no model cells nearby are
                LIFTED (cells synthesised along the origin->insertion line).

HONEST SCOPE: the vertebrae are genuinely restriction-then-lift (identity from the model's clock+Hox). The
muscles are assigned by anatomical ADDRESS (proximity), NOT yet generated by a connective-tissue-scaffold
head -- individual muscles are really carved by CT cleavage planes (Tcf4 scaffold), the missing primitive.
So "muscle for muscle" here = every named muscle present + occupied, not yet developmentally derived.

Run: cd cognimed && venv_win_new/Scripts/python.exe -m medic.part_resolved_anatomy
Out: data/organ_cascade/part_resolved_anatomy.{png,json}
"""
from __future__ import annotations
import json
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from medic.adult_persistence_audit import build_base
from medic.unified_embryo import FIDX
from medic.vertebral_column import build_column, FORMULA
from medic.axial_skeleton import vertebra_names, region_of, REGION_COL, N_VERT, atlas_vertebra_ap
from medic.human_movie import _atlas_to_laid
from menagerie.targets import reference_genome
from menagerie.skeleton import build_skeleton
from menagerie.muscles import build_muscles


def _norm(P):
    """Per-axis min-max to [0,1] (AP,DV,ML fractions) -- a frame-robust common space for assignment."""
    lo = P.min(0); span = np.ptp(P, 0) + 1e-9
    return (P - lo) / span


# ------------------------------------------------------------------ vertebrae: complete all 30
def complete_column(base, F, rng):
    zmax = np.abs(base[:, 2]).max()
    cart = (F == FIDX["Cartilage"]) & (np.abs(base[:, 2]) < 0.18 * zmax)
    noto = F == FIDX["Notochord"] if "Notochord" in FIDX else cart
    P = base[cart].copy(); P[:, 0] = -P[:, 0]                    # anterior -> t=0
    axis = base[noto].copy(); axis[:, 0] = -axis[:, 0]          # the axial centre-line the empties sit on
    t, vert, _ = build_column(P, n_vert=N_VERT)
    names = vertebra_names()
    cell_name = np.array([names[v] for v in vert])

    # map segment index -> AP fraction on the axial centre-line (so lifted centra sit on the axis)
    ax_t = (axis[:, 0] - axis[:, 0].min()) / (np.ptp(axis[:, 0]) + 1e-9)
    order = np.argsort(ax_t)
    out_pts, out_name, out_real = [], [], []
    for i, nm in enumerate(names):
        m = cell_name == nm
        if m.sum() >= 3:
            out_pts.append(P[m]); out_name += [nm] * int(m.sum()); out_real += [True] * int(m.sum())
        else:
            # LIFT: synthesise a small centrum on the axis at this vertebra's AP level
            frac = (i + 0.5) / N_VERT
            k = order[int(np.clip(frac * (len(order) - 1), 0, len(order) - 1))]
            c = axis[k]
            blob = c + rng.normal(size=(8, 3)) * np.array([0.01, 0.02, 0.02]) * (np.ptp(P[:, 0]) + 1e-9)
            out_pts.append(blob); out_name += [nm] * 8; out_real += [False] * 8
    V = np.vstack(out_pts)
    V[:, 0] = -V[:, 0]            # UN-NEGATE AP back to the base frame. The column is built in a flipped-AP
    # frame (anterior->t=0 for naming); if it is returned flipped, warp()/kNN-to-base grabs cells at the
    # OPPOSITE end of the body and the whole spine detaches from the trunk (the floating vertebral column).
    Vname = np.array(out_name); Vreal = np.array(out_real)

    # NEURAL ARCH: the centrum sits on the notochord (ventral); each vertebra also grows a neural arch DORSALLY
    # that encircles the spinal cord -- the vertebral canal. Without it the column is a row of centra ventral to
    # the cord and the cord does not thread it. Grow, per vertebra, a few arch points bridging its centrum toward
    # the cord at that AP level, so the cord runs through the canal (Gray's: the vertebral foramina form the canal).
    cord_ids = [FIDX[n] for n in ("Spinal Cord", "Nervous System", "Neural tube") if n in FIDX]
    cord = base[np.isin(F, cord_ids)] if cord_ids else base[:0]
    if len(cord) > 8:
        Hap = np.ptp(base[:, 0]) + 1e-9
        add_pts, add_nm = [], []
        for nm in names:
            vm = Vname == nm
            if not vm.any():
                continue
            vc = V[vm].mean(0)
            near = cord[np.abs(cord[:, 0] - vc[0]) < 0.03 * Hap]      # cord at this vertebra's AP level
            if len(near) == 0:
                continue
            cc = near.mean(0)
            ts = np.linspace(0.45, 1.0, 4)[:, None]                  # bridge centrum -> cord (the arch)
            arch = vc[None] * (1 - ts) + cc[None] * ts + rng.normal(size=(4, 3)) * 0.005
            add_pts.append(arch); add_nm += [nm] * 4
        if add_pts:
            V = np.vstack([V] + add_pts)
            Vname = np.concatenate([Vname, np.array(add_nm)])
            Vreal = np.concatenate([Vreal, np.zeros(sum(len(a) for a in add_pts), bool)])

    populated = len({n for n in Vname})
    real_v = len({n for n, r in zip(Vname, Vreal) if r})
    return V, Vname, Vreal, populated, real_v, names


# ------------------------------------------------------------------ muscles: assign to the 31 Hill-muscles
def assign_muscles(base, F, rng):
    mus = base[F == FIDX["Muscle"]] if "Muscle" in FIDX else base[:0]
    g = reference_genome("human_male")
    bones = build_skeleton(g)
    muscles = build_muscles(g, bones)
    mid = np.array([_atlas_to_laid(((m.origin + m.insertion) / 2)[None])[0] for m in muscles])   # atlas muscle midpoints, laid
    names = [m.name for m in muscles]
    if not len(mus):
        return np.zeros((0, 3)), np.array([]), names, 0
    # assign each model muscle cell to the nearest atlas muscle in normalised AP/DV/ML space
    nm_model = _norm(mus); nm_atlas = _norm(mid)
    # nearest atlas muscle for each model cell
    d = ((nm_model[:, None, :] - nm_atlas[None, :, :]) ** 2).sum(-1)
    assign = d.argmin(1)
    cell_musc = np.array([names[a] for a in assign])
    populated = len(set(cell_musc))
    # LIFT the muscles that got no model cells: synthesise cells along origin->insertion
    got = set(cell_musc)
    lift_pts, lift_nm = [], []
    for m in muscles:
        if m.name in got:
            continue
        o = _atlas_to_laid(m.origin[None])[0]; i = _atlas_to_laid(m.insertion[None])[0]
        ts = np.linspace(0, 1, 8)[:, None]
        seg = o[None] * (1 - ts) + i[None] * ts + rng.normal(size=(8, 3)) * 0.01
        lift_pts.append(seg); lift_nm += [m.name] * 8
    return mus, cell_musc, names, populated, (np.vstack(lift_pts) if lift_pts else np.zeros((0, 3))), np.array(lift_nm)


def _figure(V, Vname, Vreal, names, mus, cell_musc, mnames, mlift, mlift_nm):
    fig, ax = plt.subplots(1, 2, figsize=(14, 7), facecolor="#0d1017")
    for a in ax:
        a.set_facecolor("#0d1017"); a.set_aspect("equal"); a.axis("off")
    # vertebrae: real = bright region colour, lifted = dim grey
    for nm in names:
        m = Vname == nm
        if not m.any():
            continue
        real = Vreal[m][0]
        col = REGION_COL[region_of(nm)] if real else "#3a4150"
        ax[0].scatter(V[m, 0], V[m, 1], s=16, c=col)
    ax[0].set_title(f"vertebral column COMPLETE: {len({n for n in Vname})}/30\n"
                    f"bright = model's cells · grey = lifted from capsule", color="#7dd3fc", fontsize=10)
    # muscles: colour each model muscle cell by its assigned muscle (hash to a colour)
    if len(mus):
        idx = np.array([hash(n) % 20 for n in cell_musc])
        ax[1].scatter(mus[:, 0], mus[:, 1], s=6, c=idx, cmap="tab20", alpha=0.7)
    if len(mlift):
        ax[1].scatter(mlift[:, 0], mlift[:, 1], s=6, c="#3a4150", alpha=0.6)
    npop = len(set(cell_musc)) if len(cell_musc) else 0
    ax[1].set_title(f"Hill-muscles: {npop}/{len(mnames)} occupied by model myotome\n"
                    f"coloured = model cells (per muscle) · grey = lifted", color="#f0a5a5", fontsize=10)
    fig.suptitle("Part-resolved anatomy: the model's own cells lifted into the atlas's named vertebrae + Hill-muscles",
                 color="#e2e8f0", fontsize=11)
    fig.tight_layout()
    os.makedirs("data/organ_cascade", exist_ok=True)
    fig.savefig("data/organ_cascade/part_resolved_anatomy.png", dpi=120, facecolor="#0d1017")
    print("saved data/organ_cascade/part_resolved_anatomy.png")


def main():
    rng = np.random.default_rng(0)
    base, F = build_base()
    V, Vname, Vreal, vpop, vreal, names = complete_column(base, F, rng)
    print(f"VERTEBRAE: {vpop}/30 populated ({vreal} from the model's own cartilage, {vpop - vreal} lifted)")
    mus, cell_musc, mnames, mpop, mlift, mlift_nm = assign_muscles(base, F, rng)
    print(f"MUSCLES  : {mpop}/{len(mnames)} Hill-muscles occupied by the model's myotome "
          f"({len(mnames) - mpop} lifted); {len(mus)} muscle cells assigned")
    _figure(V, Vname, Vreal, names, mus, cell_musc, mnames, mlift, mlift_nm)
    from collections import Counter
    json.dump(dict(vertebrae_populated=vpop, vertebrae_from_model=vreal,
                   muscles_total=len(mnames), muscles_populated=mpop,
                   muscle_cells=len(mus), top_muscles=Counter(cell_musc.tolist()).most_common(8)),
              open("data/organ_cascade/part_resolved_anatomy.json", "w"), indent=1)
    print("saved data/organ_cascade/part_resolved_anatomy.json")


if __name__ == "__main__":
    main()
